/* 67 — authoritative client. Backend + DB are the source of truth for PvP. */
(() => {
  'use strict';
  const ROUND_MS = 6700, MATCH_MS = 6700, STORE = 'six-seven::state-v1', PID = 'six-seven::player-id';
  const tg = window.Telegram?.WebApp;
  tg?.ready?.(); tg?.expand?.(); tg?.disableVerticalSwipes?.();
  const hands = [
    ['hand','CLASSIC','assets/hand.png',0,'common'], ['clown','JOKER','assets/clown.png',500,'rare'], ['cube','BLOCKY','assets/cube.png',700,'rare'],
    ['spanch','SPONGE','assets/spanch.png',1200,'epic'], ['devil','DEMON','assets/devil.png',1500,'epic'], ['roblox','BLOX','assets/roblox.png',2400,'legend'], ['robo','CYBORG','assets/robo.png',3000,'legend'],
  ].map(([id,name,img,price,rarity]) => ({ id, name, img, price, rarity }));
  const digits = [ ['classic','CLASSIC',0,'common'], ['clown','JOKER',650,'rare'], ['devil','DEMON',1100,'epic'], ['robo','CYBORG',1700,'legend'] ].map(([id,name,price,rarity]) => ({ id, name, price, rarity }));
  const rivals = ['ZenBoy','Ksu_Lab','NoChill','CR1S','mishakek','Bruh666','Lola.exe','taptap','Vibez','pluh','GYAT','Spectre'];
  const D = Object.create(null), $ = id => D[id] || (D[id] = document.getElementById(id)), $$ = s => [...document.querySelectorAll(s)];
  const side = v => Number(v) === 7 ? 7 : 6, opp = v => side(v) === 7 ? 6 : 7, color = v => side(v) === 7 ? '#ff2a6d' : '#2c7df5', glow = v => side(v) === 7 ? 'rgba(255,42,109,.66)' : 'rgba(44,125,245,.66)';
  const pick = a => a[Math.floor(Math.random() * a.length)] || a[0], clamp = (v,a,b) => Math.max(a, Math.min(b, v));
  const lang = () => ([tg?.initDataUnsafe?.user?.language_code, navigator.language, ...(navigator.languages || [])].filter(Boolean).some(x => String(x).toLowerCase().startsWith('ru')) ? 'ru' : 'en');
  const i18n = {
    en:{ shop:'SHOP', fight:'FIGHT', profile:'PROFILE', top:'TOP', home:'BACK TO HOME', pick:'PICK A SIDE. TAP TO WIN.', ready:'READY?', fightFor:'FIGHT FOR', matchTitle:'FINDING OPPONENT', cancel:'CANCEL', tap:'TAP TAP TAP', you:'YOU', rival:'RIVAL', win:'VICTORY', lose:'DEFEAT', draw:'DRAW', yourTaps:'Your taps', rivalTaps:'Rival taps', reward:'Reward', hands:'HANDS', digitTab:'DIGITS', buy:'BUY', equip:'EQUIP', equipped:'EQUIPPED', noCoins:'Not enough coins', weekly:'WEEKLY TOP', stars:'10,000 TG STARS', ref:'INVITE GANG', guild:'GUILD WAR', createGuild:'CREATE GUILD', raid:'RAID A CHAT', finalRush:'FINAL RUSH!' },
    ru:{ shop:'МАГАЗИН', fight:'БОЙ', profile:'ПРОФИЛЬ', top:'ТОП', home:'НА ГЛАВНУЮ', pick:'ВЫБЕРИ СТОРОНУ. ТАПАЙ И ПОБЕЖДАЙ.', ready:'ГОТОВ?', fightFor:'БЕЙСЯ ЗА', matchTitle:'ИЩЕМ СОПЕРНИКА', cancel:'ОТМЕНА', tap:'ТАП ТАП ТАП', you:'ТЫ', rival:'СОПЕРНИК', win:'ПОБЕДА', lose:'ПОРАЖЕНИЕ', draw:'НИЧЬЯ', yourTaps:'Твои тапы', rivalTaps:'Тапы соперника', reward:'Награда', hands:'РУКИ', digitTab:'ЦИФРЫ', buy:'КУПИТЬ', equip:'ВЫБРАТЬ', equipped:'ВЫБРАНО', noCoins:'Не хватает монет', weekly:'ТОП НЕДЕЛИ', stars:'10 000 TG STARS', ref:'ПОЗВАТЬ GANG', guild:'ВОЙНА ГИЛЬДИЙ', createGuild:'СОЗДАТЬ ГИЛЬДИЮ', raid:'РЕЙД ЧАТА', finalRush:'ФИНАЛЬНЫЙ РЫВОК!' }
  };
  const tr = k => (i18n[state.lang] || i18n.en)[k] || k;
  const haptic = { light: throttle(() => tg?.HapticFeedback?.impactOccurred?.('light'), 80), med: throttle(() => tg?.HapticFeedback?.impactOccurred?.('medium'), 150), win: () => tg?.HapticFeedback?.notificationOccurred?.('success') };
  function throttle(fn, ms) { let last = 0; return (...a) => { const n = Date.now(); if (n - last < ms) return; last = n; return fn(...a); }; }
  function id(bytes = 8) { const a = new Uint8Array(bytes); crypto.getRandomValues(a); return [...a].map(x => x.toString(16).padStart(2,'0')).join(''); }
  function playerId() { let v = localStorage.getItem(PID); if (!v) { v = tg?.initDataUnsafe?.user?.id ? `tg_${tg.initDataUnsafe.user.id}` : `guest_${id(8)}`; localStorage.setItem(PID, v); } return v; }
  const defaults = { playerId: playerId(), name: tg?.initDataUnsafe?.user?.first_name || 'Alpha67', side: 6, hand: 'hand', digitStyle: 'classic', coins: 250, ownedHands: ['hand'], ownedDigits: ['classic'], weeklyScore: 0, stats: { wins:0, losses:0, ties:0, best:0, totalTaps:0, currentStreak:0, streakType:'none' }, referrals:{ code:`g${id(3)}`, sent:0, accepted:0 }, guild:{ id:'', name:'', tag:'', side:6, score:0, members:0 }, lang: lang() };
  let state = load();
  function load() { try { return { ...defaults, ...JSON.parse(localStorage.getItem(STORE) || '{}') }; } catch { return { ...defaults }; } }
  function save() { try { localStorage.setItem(STORE, JSON.stringify(state)); } catch {} }
  state.playerId ||= playerId(); state.side = side(state.side); state.lang = lang(); state.ownedHands = [...new Set(['hand', ...(state.ownedHands || [])])]; state.ownedDigits = [...new Set(['classic', ...(state.ownedDigits || [])])]; state.stats = { ...defaults.stats, ...(state.stats || {}) }; save();
  const perf = /iPhone|iPad|iPod/i.test(navigator.userAgent) || (navigator.hardwareConcurrency && navigator.hardwareConcurrency <= 4) || matchMedia('(prefers-reduced-motion: reduce)').matches;
  document.body.classList.toggle('perf-lite', perf);
  injectCss();

  const api = {
    async get(url) { const r = await fetch(url); if (!r.ok) throw new Error(await r.text()); return r.json(); },
    async post(url, body) { const r = await fetch(url, { method:'POST', headers:{ 'content-type':'application/json' }, body:JSON.stringify(body) }); if (!r.ok) throw new Error(await r.text()); return r.json(); },
    profile() { return { playerId:state.playerId, name:state.name, side:state.side, hand:state.hand, digitStyle:state.digitStyle }; },
    async sync() { const { player } = await this.post('/api/profile', this.profile()); applyServerPlayer(player); return player; }
  };
  function applyServerPlayer(p) { if (!p) return; state.name=p.name||state.name; state.side=side(p.side||state.side); state.hand=p.hand||state.hand; state.digitStyle=p.digitStyle||state.digitStyle; state.coins=Number(p.coins??state.coins); state.weeklyScore=Number(p.weeklyScore??state.weeklyScore); state.stats={ ...state.stats, ...(p.stats||{}) }; state.ownedHands=[...new Set(['hand', ...(p.inventory?.hands||state.ownedHands||[])])]; state.ownedDigits=[...new Set(['classic', ...(p.inventory?.digits||state.ownedDigits||[])])]; save(); renderAll(); }

  const rt = { ws:null, connected:false, connecting:null, offset:0, sessionId:'', send(msg){ if (this.ws?.readyState === WebSocket.OPEN) this.ws.send(JSON.stringify(msg)); }, connect(){ if (this.connected && this.ws?.readyState === WebSocket.OPEN) return Promise.resolve(); if (this.connecting) return this.connecting; this.connecting = new Promise((resolve,reject) => { const ws = new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`); this.ws=ws; const fail=setTimeout(()=>reject(new Error('ws timeout')), 7000); ws.onopen=()=>{ clearTimeout(fail); this.connected=true; this.connecting=null; this.send({ type:'hello', ...api.profile() }); resolve(); }; ws.onmessage=e=>onWs(e.data); ws.onclose=()=>{ this.connected=false; this.connecting=null; if (battle.active && !battle.finished) toast(state.lang==='ru'?'Связь потеряна. Сервер сохранит бой.':'Connection lost. Server keeps the match.'); }; ws.onerror=()=>{}; }); return this.connecting; } };
  const serverNow = () => Date.now() + rt.offset;
  function onWs(raw) { let m; try { m=JSON.parse(raw); } catch { return; } if (m.serverNow) rt.offset = m.serverNow - Date.now(); if (m.type==='hello:required') rt.sessionId=m.sessionId; if (m.type==='hello:ack') applyServerPlayer(m.player); if (m.type==='server:sync') return; if (m.type==='matchmaking:queued') return showQueued(m); if (m.type==='matchmaking:cancelled') { if (screen==='matching') showScreen('home'); return; } if (m.type==='match:found') return startBattle(m.match); if (m.type==='match:score') return updateScore(m); if (m.type==='match:result') return finishBattle(m.match, m.player); }

  let screen = 'home', rafMatch = 0, rafBattle = 0, activeFloaters = 0, shopTab = 'hands', topTab = 'players';
  const battle = { active:false, finished:false, id:'', you:'a', startsAt:0, endsAt:0, scores:{ a:0, b:0 }, parts:[] };
  function showScreen(name) { screen = name; $$('[data-screen]').forEach(s => { s.hidden = s.dataset.screen !== name; }); $$('.nav-item').forEach(b => b.classList.toggle('is-active', b.dataset.nav === name || (name==='battle' && b.dataset.nav==='battle-quick'))); cancelAnimationFrame(rafMatch); cancelAnimationFrame(rafBattle); if (name === 'top') renderTop(); }
  function setText(id, v) { const el=$(id); if (el) el.textContent = v; }
  function img(id, src) { const el=$(id); if (el) el.src = src; }
  function digitSrc(n = state.side) { return `assets/digits/${state.digitStyle}-${side(n)}.png`; }
  function renderAll() { document.documentElement.lang = state.lang; $$('[data-i18n]').forEach(el => { const k = el.dataset.i18n; const map = { 'topbar.shop':'shop','hero.tag':'pick','cta.ready':'ready','cta.fightFor':'fightFor','cta.sub':'tap','ref.invite':'ref','guild.eyebrow':'guild','guild.create':'createGuild','matching.title':'matchTitle','common.cancel':'cancel','common.home':'home','battle.tap':'tap','result.yourTaps':'yourTaps','result.rivalTaps':'rivalTaps','result.reward':'reward','result.raid':'raid','shop.title':'shop','shop.hands':'hands','shop.digits':'digitTab','top.title':'weekly','profile.title':'profile','nav.profile':'profile','nav.fight':'fight','nav.top':'top' }; if (map[k]) el.textContent = tr(map[k]); });
    setText('user-name', state.name); setText('user-coins', state.coins); setText('shop-coins', state.coins); setText('home-battle-side', state.side); setText('profile-name', state.name); setText('profile-wins', state.stats.wins); setText('profile-losses', state.stats.losses); setText('profile-best', state.stats.best); setText('user-level', `L${Math.max(1, Math.floor((state.stats.totalTaps||0)/300)+1)}`); setText('user-rank', rank()); setText('profile-rank', rank());
    $$('.side-btn').forEach(b => b.classList.toggle('is-selected', side(b.dataset.side) === state.side)); const cta=$('home-battle-cta'); if (cta) cta.dataset.side=state.side;
    img('hero-hand-left', hands.find(h=>h.id===state.hand)?.img || 'assets/hand.png'); img('hero-hand-right', hands.find(h=>h.id===state.hand)?.img || 'assets/hand.png'); img('hero-digit-6', digitSrc(6)); img('hero-digit-7', digitSrc(7));
    renderRef(); renderGuild(); renderWar(); if (screen==='shop') renderShop(); }
  function rank(){ const w=Number(state.stats.wins||0), t=Number(state.stats.totalTaps||0); if(w>=67||t>=6700) return 'LEGEND'; if(w>=25||t>=2400) return 'CHAMPION'; if(w>=10||t>=900) return 'CONTENDER'; if(w>=3||t>=250) return 'STREET FIGHTER'; return 'RECRUIT'; }
  async function renderWar(){ try { const w=await api.get('/api/global-war'); const total=Math.max(1,w.six+w.seven); const s=100*w.six/total; $('war-six').style.width=`${s}%`; $('war-seven').style.width=`${100-s}%`; setText('war-six-pct', `${s.toFixed(1)}%`); setText('war-seven-pct', `${(100-s).toFixed(1)}%`); setText('war-participation', (w.six+w.seven).toLocaleString('ru-RU')); } catch {} }
  function renderRef(){ setText('ref-title', state.referrals.accepted>=67?'RAID CAPTAIN':state.referrals.accepted>=6?'GANG STARTER':state.referrals.accepted>=1?'SCOUT':'NO CROWD'); setText('ref-count', state.referrals.accepted||0); const p=$('ref-progress'); if(p) p.style.width=`${clamp((state.referrals.accepted||0)/67*100,0,100)}%`; }
  function renderGuild(){ setText('guild-title', state.guild.id ? state.guild.name : (state.lang==='ru'?'НЕТ ГИЛЬДИИ':'NO GUILD')); setText('guild-badge', state.guild.tag || 'G'); setText('guild-score', state.guild.score||0); setText('guild-members', state.guild.members||0); setText('guild-reward', state.guild.id ? 67 : 0); }
  function setSide(v){ state.side=side(v); save(); renderAll(); spawnHomeDigit(innerWidth*.5, innerHeight*.52); haptic.med(); }

  async function startMatchmaking(){ haptic.med(); showScreen('matching'); img('matching-side', digitSrc(state.side)); setText('matching-status', state.lang==='ru'?'Ищем живого соперника 6.7 сек…':'Looking for live rival for 6.7s…'); try { await api.sync(); await rt.connect(); rt.send({ type:'matchmaking:join', profile:api.profile() }); } catch(e) { toast(state.lang==='ru'?'Бэкенд недоступен':'Backend unavailable'); showScreen('home'); } }
  function showQueued(m){ const deadline = m.deadlineAt; const loop=()=>{ const left=Math.max(0, deadline-serverNow()); setText('matching-status', `${state.lang==='ru'?'Live PvP':'Live PvP'}: ${(left/1000).toFixed(1)}s → BOT`); if(left>0 && screen==='matching') rafMatch=requestAnimationFrame(loop); }; loop(); }
  function cancelMatching(){ rt.send({ type:'matchmaking:cancel' }); showScreen('home'); }
  function startBattle(m){ Object.assign(battle, { active:true, finished:false, id:m.id, you:m.youSlot, startsAt:m.startsAt, endsAt:m.endsAt, scores:{...m.scores}, parts:m.participants }); const me=m.participants.find(p=>p.slot===m.youSlot), enemy=m.participants.find(p=>p.slot!==m.youSlot); showScreen('battle'); setText('me-name', tr('you')); setText('enemy-name', enemy?.name || tr('rival')); $('card-me').dataset.side=me?.side||state.side; $('card-enemy').dataset.side=enemy?.side||opp(state.side); img('me-side', digitSrc(me?.side || state.side)); img('enemy-side', `assets/digits/${enemy?.digitStyle||state.digitStyle}-${enemy?.side||opp(state.side)}.png`); img('battle-hand-left', hands.find(h=>h.id===(me?.hand||state.hand))?.img || 'assets/hand.png'); img('battle-hand-right', hands.find(h=>h.id===(enemy?.hand||state.hand))?.img || 'assets/hand.png'); img('battle-digit', digitSrc(me?.side || state.side)); updateScore({ matchId:m.id, scores:m.scores }); animateBattle(); }
  function animateBattle(){ const tick=()=>{ const n=serverNow(); const left=battle.startsAt>n ? battle.startsAt-n : Math.max(0,battle.endsAt-n); const live=n>=battle.startsAt && n<battle.endsAt; setText('timer-num', battle.startsAt>n ? Math.ceil((battle.startsAt-n)/1000) : (left/1000).toFixed(1)); setText('battle-meme', battle.startsAt>n ? (state.lang==='ru'?'ПРИГОТОВЬСЯ':'GET READY') : left<1300 ? tr('finalRush') : 'SIX • SEVEN • TAP!'); const fg=$('timer-fg'); if(fg){ const progress = live ? left/ROUND_MS : 1; fg.style.strokeDasharray='276'; fg.style.strokeDashoffset=String(276*(1-progress)); } if(!battle.finished && screen==='battle') rafBattle=requestAnimationFrame(tick); }; tick(); }
  function updateScore(m){ if(m.matchId && m.matchId!==battle.id) return; battle.scores={...battle.scores, ...m.scores}; const my=battle.scores[battle.you]||0, otherSlot=battle.parts.find(p=>p.slot!==battle.you)?.slot, enemy=battle.scores[otherSlot]||0; setText('me-score', my); setText('enemy-score', enemy); const total=Math.max(1,my+enemy); const meSide=battle.parts.find(p=>p.slot===battle.you)?.side || state.side; $('vs-bar-six').style.width = `${meSide===6 ? my/total*100 : enemy/total*100}%`; $('vs-bar-seven').style.width = `${meSide===7 ? my/total*100 : enemy/total*100}%`; if(my===67) jackpot(); }
  function tapBattle(e){ if(!battle.active || battle.finished) return; const n=serverNow(); if(n<battle.startsAt || n>=battle.endsAt) return; rt.send({ type:'tap', matchId:battle.id }); spawnBattleFx(e.clientX || innerWidth/2, e.clientY || innerHeight/2); haptic.light(); }
  function finishBattle(record, player){ if(!record || record.id!==battle.id) return; battle.finished=true; battle.active=false; cancelAnimationFrame(rafBattle); const my=battle.you, myScore=record.scores[my]||0, enemySlot=Object.keys(record.scores).find(s=>s!==my), enemyScore=record.scores[enemySlot]||0; const won=record.winnerSlot===my, draw=record.winnerSlot==null; setText('result-verdict', draw?tr('draw'):won?tr('win'):tr('lose')); setText('result-subtitle', `${record.bot?'BOT FALLBACK':'LIVE PVP'} • SERVER MATCH ${record.id.slice(-6)}`); setText('result-my-score', myScore); setText('result-enemy-score', enemyScore); setText('result-reward', won ? 50+Math.floor(myScore*.8) : draw ? 20 : 10); img('result-side', digitSrc(state.side)); const title=$('result-callout-title'), text=$('result-callout-text'), streak=$('result-streak'); if(title) title.textContent = myScore===67 ? 'SIX SEVEN JACKPOT' : won ? 'SERVER VERIFIED W' : draw ? 'SERVER VERIFIED DRAW' : 'SERVER VERIFIED L'; if(text) text.textContent = state.lang==='ru' ? 'Результат записан в БД и одинаков для обоих клиентов.' : 'Result is saved in DB and identical for both clients.'; if(streak) streak.textContent = `BEST ${Math.max(state.stats.best||0,myScore)}`; applyServerPlayer(player); haptic.win(); showScreen('result'); }

  let jackpotShown = false;
  function spawnHomeDigit(x,y){ if (screen !== 'home') return; const el=document.createElement('b'); const n=Math.random()<.5?6:7; el.className='home-float-digit'; el.textContent=n; el.style.left=`${x||Math.random()*innerWidth}px`; el.style.top=`${y||Math.random()*innerHeight}px`; el.style.color=color(state.side); el.style.textShadow=`0 0 18px ${glow(state.side)}`; document.body.appendChild(el); setTimeout(()=>el.remove(),900); }
  function spawnBattleFx(x,y){ if(activeFloaters > (perf ? 16 : 36)) return; activeFloaters++; const words=['6','7','SIX','SEVEN','AURA','BRAINROT']; const el=document.createElement('i'); el.className='battle-fx'; el.textContent=pick(words); el.style.left=`${x}px`; el.style.top=`${y}px`; el.style.color=color(state.side); el.style.setProperty('--dx', `${(Math.random()-.5)*160}px`); $('battle-floaters')?.appendChild(el); setTimeout(()=>{ activeFloaters--; el.remove(); },650); }
  function jackpot(){ if(jackpotShown) return; jackpotShown=true; const box=document.createElement('div'); box.className='jackpot67'; box.innerHTML='<b>67</b><span>SIX SEVEN BRAINROT</span>'; document.body.appendChild(box); for(let i=0;i<(perf?12:28);i++) setTimeout(()=>spawnBattleFx(Math.random()*innerWidth, Math.random()*innerHeight*.8), i*12); setTimeout(()=>box.remove(),1200); }

  function renderShop(){ const grid=$('shop-grid'); if(!grid) return; grid.innerHTML=''; const list=shopTab==='hands'?hands:digits, owned=shopTab==='hands'?state.ownedHands:state.ownedDigits, equipped=shopTab==='hands'?state.hand:state.digitStyle; list.forEach(item=>{ const card=document.createElement('button'); card.className='shop-card'; const src=shopTab==='hands'?item.img:`assets/digits/${item.id}-${state.side}.png`; const own=owned.includes(item.id); card.innerHTML=`<img src='${src}' alt=''><b>${item.name}</b><small>${item.rarity.toUpperCase()}</small><span>${own ? (equipped===item.id?tr('equipped'):tr('equip')) : `${tr('buy')} 🪙 ${item.price}`}</span>`; card.onclick=()=>shopAction(shopTab,item.id,own,equipped===item.id); grid.appendChild(card); }); }
  async function shopAction(kind,itemId,owned,equipped){ try { if(!owned){ const { player }=await api.post('/api/shop/buy',{ playerId:state.playerId, kind, itemId }); applyServerPlayer(player); } if(!equipped){ const { player }=await api.post('/api/shop/equip',{ playerId:state.playerId, kind, itemId }); applyServerPlayer(player); } renderShop(); haptic.med(); } catch { toast(tr('noCoins')); } }
  async function renderTop(){ const list=$('top-list'); if(!list) return; list.innerHTML=`<div class='top-row'><span class='top-row__name'>Loading…</span></div>`; try { const data=await api.get('/api/leaderboard/weekly'); let rows=data.players || []; while(rows.length<100){ const r=rows.length+1; rows.push({ rank:r, name:pick(rivals), side: r%2?6:7, score:Math.max(0,67000-r*513), prizeStars:(data.prizes||{})[r]||0 }); } list.innerHTML=rows.slice(0,100).map(r=>`<div class='top-row ${r.id===state.playerId?'is-me':''} ${r.rank===67?'top-row--lucky67':''}'><span class='top-row__rank ${r.rank===1?'gold':r.rank===2?'silver':r.rank===3?'bronze':r.rank===67?'lucky':''}'>#${r.rank}</span><span class='top-row__name'>${escapeHtml(r.name)}</span><span class='top-row__side' data-side='${r.side}'>${r.side}</span><span class='top-row__score'>${Number(r.score||0).toLocaleString('ru-RU')}</span>${r.prizeStars?`<span class='top-row__prize'>⭐ ${r.prizeStars}</span>`:''}</div>`).join(''); setText('reset-in', tr('stars')); } catch { list.innerHTML=`<div class='top-row'><span class='top-row__name'>Backend offline</span></div>`; } }
  function escapeHtml(s){ return String(s||'').replace(/[&<>]/g,c=>({ '&':'&amp;','<':'&lt;','>':'&gt;' }[c])); }
  function toast(text){ let el=$('toast'); if(!el){ el=document.createElement('div'); el.id='toast'; document.body.appendChild(el); } el.textContent=text; el.classList.add('show'); clearTimeout(toast.t); toast.t=setTimeout(()=>el.classList.remove('show'),1600); }
  function shareReferral(){ state.referrals.sent=(state.referrals.sent||0)+1; save(); const url=`${location.origin}${location.pathname}?tgWebAppStartParam=r_${state.referrals.code}_${state.side}`; const share=`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(`I picked ${state.side} GANG. Beat me in 6.7 sec.`)}`; tg?.openTelegramLink?.(share) || window.open(share,'_blank','noopener'); renderRef(); }
  function injectCss(){ const css=`
    .home-float-digit{position:fixed;z-index:80;font-family:var(--font-loud,var(--font-display));font-size:52px;pointer-events:none;transform:translate(-50%,-50%);animation:homeDigit .9s cubic-bezier(.2,.8,.2,1) forwards}.battle-fx{position:absolute;z-index:8;font-family:var(--font-loud,var(--font-display));font-size:clamp(20px,7vw,42px);font-style:normal;font-weight:900;pointer-events:none;text-shadow:0 3px 0 rgba(0,0,0,.12);animation:battleFx .65s ease-out forwards}.jackpot67{position:fixed;inset:0;z-index:100;display:grid;place-items:center;background:radial-gradient(circle,rgba(255,184,0,.38),rgba(255,42,109,.22),transparent 72%);pointer-events:none;animation:jackBg 1.2s ease-out forwards}.jackpot67 b{font-family:var(--font-loud);font-size:min(40vw,190px);line-height:.8;color:#fff;text-shadow:0 8px 0 rgba(0,0,0,.14),0 0 30px #ffb800}.jackpot67 span{position:absolute;top:62%;font-family:var(--font-display);font-size:18px;letter-spacing:2px;color:#111128;background:#ffb800;border-radius:999px;padding:10px 16px}.shop-card{min-height:170px;padding:12px;border-radius:22px;background:#fff;box-shadow:var(--shadow-lift);display:flex;flex-direction:column;align-items:center;justify-content:space-between;gap:6px}.shop-card img{height:76px;object-fit:contain}.shop-card b{font-family:var(--font-display);font-size:13px}.shop-card small{font-size:10px;color:var(--muted);font-weight:900}.shop-card span{width:100%;border-radius:14px;padding:9px 8px;background:linear-gradient(135deg,var(--six),var(--seven));color:white;font-family:var(--font-display);font-size:10px}.perf-lite .bg-particle,.perf-lite .spark,.perf-lite .ring,.perf-lite .bg-ghost{animation:none!important}.perf-lite .battle__speedlines{opacity:.18}#toast{position:fixed;left:50%;bottom:calc(90px + env(safe-area-inset-bottom,0px));z-index:200;transform:translateX(-50%) translateY(20px);opacity:0;background:#111128;color:#fff;border-radius:999px;padding:10px 16px;font-family:var(--font-display);font-size:12px;transition:160ms ease;box-shadow:0 12px 28px rgba(0,0,0,.24)}#toast.show{opacity:1;transform:translateX(-50%) translateY(0)}@keyframes homeDigit{0%{opacity:0;scale:.4;translate:0 12px}20%{opacity:1;scale:1.1}100%{opacity:0;scale:.9;translate:0 -92px;rotate:18deg}}@keyframes battleFx{0%{opacity:0;scale:.35;transform:translate(-50%,-50%)}18%{opacity:1;scale:1.08}100%{opacity:0;transform:translate(calc(-50% + var(--dx,0px)),-110px) rotate(14deg);scale:.9}}@keyframes jackBg{0%{opacity:0;scale:.86}18%{opacity:1;scale:1.02}100%{opacity:0;scale:1.12}}`;
    const st=document.createElement('style'); st.textContent=css; document.head.appendChild(st); }

  document.addEventListener('pointerdown', e => { if (screen==='home') spawnHomeDigit(e.clientX, e.clientY); }, { passive:true });
  $$('.side-btn').forEach(b => b.addEventListener('click', () => setSide(b.dataset.side)));
  $('home-battle-cta')?.addEventListener('click', startMatchmaking);
  $('matching-cancel')?.addEventListener('click', cancelMatching);
  $('tap-zone')?.addEventListener('pointerdown', tapBattle, { passive:true });
  $('result-home')?.addEventListener('click', () => { jackpotShown=false; showScreen('home'); renderAll(); });
  $('ref-invite')?.addEventListener('click', shareReferral);
  $('guild-create')?.addEventListener('click', () => { const name=prompt(state.lang==='ru'?'Название гильдии':'Guild name') || `GANG ${state.side}`; state.guild={ id:`g_${id(3)}`, name:name.slice(0,20), tag:name.replace(/[^A-Za-zА-Яа-я0-9]/g,'').toUpperCase().slice(0,3)||'GNG', side:state.side, score:67, members:1 }; save(); renderGuild(); });
  $$('[data-nav]').forEach(b => b.addEventListener('click', () => b.dataset.nav==='battle-quick' ? startMatchmaking() : showScreen(b.dataset.nav)));
  $$('[data-go-home]').forEach(b => b.addEventListener('click', () => showScreen('home')));
  $$('.shop-tab').forEach(b => b.addEventListener('click', () => { shopTab=b.dataset.shopTab; $$('.shop-tab').forEach(x=>x.classList.toggle('is-active',x===b)); renderShop(); }));
  $$('.top-tab').forEach(b => b.addEventListener('click', () => { topTab=b.dataset.topTab; $$('.top-tab').forEach(x=>x.classList.toggle('is-active',x===b)); renderTop(); }));
  $('open-shop-top')?.addEventListener('click', () => { showScreen('shop'); renderShop(); });
  $('open-profile-top')?.addEventListener('click', () => showScreen('profile'));
  window.addEventListener('visibilitychange', () => { if(document.hidden){ cancelAnimationFrame(rafBattle); cancelAnimationFrame(rafMatch); } else if(screen==='battle' && battle.active) animateBattle(); });
  api.sync().catch(()=>{}).finally(() => { renderAll(); showScreen('home'); });
})();
